from .cert import CertModelView
from .home_view import HomeView
from .message import MessageModelView
from .method_doc import MethodDocModelView
from .orgadmdoc import OrgAdmDocModelView
from .organization import OrganizationModelView
from .resource import ResourceModelView
from .responsibility import ResponseModelView
from .workspace import WorkspaceView
