"""short_name added to MethodicalDoc

Revision ID: 2a1af46743ed
Revises: 19f8924404fa
Create Date: 2023-02-07 10:29:27.935056

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '2a1af46743ed'
down_revision = '19f8924404fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('methodical_docs', sa.Column('short_name', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('methodical_docs', 'short_name')
    # ### end Alembic commands ###
