"""removed old resp table created lots more

Revision ID: 368c414a735a
Revises: 96f5f0d0fe36
Create Date: 2024-02-02 09:17:55.115861

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '368c414a735a'
down_revision = '96f5f0d0fe36'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('services',
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('service_id')
    )
    op.create_table('responsibilities_with_certs',
    sa.Column('resp_id', sa.Integer(), nullable=False),
    sa.Column('cert_id', sa.Integer(), nullable=False),
    sa.Column('resource_id', sa.Integer(), nullable=False),
    sa.Column('date_start', sa.Date(), nullable=False),
    sa.Column('date_end', sa.Date(), nullable=False),
    sa.Column('props', sa.Text(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['cert_id'], ['certs.cert_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resource_id'], ['resources.resource_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('resp_id'),
    sa.UniqueConstraint('resp_id')
    )
    op.create_index(op.f('ix_responsibilities_with_certs_date_end'), 'responsibilities_with_certs', ['date_end'], unique=False)
    op.create_index(op.f('ix_responsibilities_with_certs_date_start'), 'responsibilities_with_certs', ['date_start'], unique=False)
    op.create_table('responsibilities_services',
    sa.Column('service_id', sa.Integer(), nullable=True),
    sa.Column('resp_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['resp_id'], ['responsibilities_with_certs.resp_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['service_id'], ['services.service_id'], ondelete='CASCADE')
    )
    op.drop_index('ix_responsibilities_date_end', table_name='responsibilities')
    op.drop_index('ix_responsibilities_date_start', table_name='responsibilities')
    op.drop_table('responsibilities')
    op.drop_index('ix_resources_category', table_name='resources')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_resources_category', 'resources', ['category'], unique=False)
    op.create_table('responsibilities',
    sa.Column('org_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('resource_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('date_start', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('date_end', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('props', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('comment', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.org_id'], name='responsibilities_org_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resource_id'], ['resources.resource_id'], name='responsibilities_resource_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('org_id', 'resource_id', 'date_end', name='responsibilities_pkey')
    )
    op.create_index('ix_responsibilities_date_start', 'responsibilities', ['date_start'], unique=False)
    op.create_index('ix_responsibilities_date_end', 'responsibilities', ['date_end'], unique=False)
    op.drop_table('responsibilities_services')
    op.drop_index(op.f('ix_responsibilities_with_certs_date_start'), table_name='responsibilities_with_certs')
    op.drop_index(op.f('ix_responsibilities_with_certs_date_end'), table_name='responsibilities_with_certs')
    op.drop_table('responsibilities_with_certs')
    op.drop_table('services')
    # ### end Alembic commands ###
