"""added mailing address to Organization

Revision ID: 4639870c527e
Revises: d411ef171a52
Create Date: 2024-01-30 14:22:15.394352

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '4639870c527e'
down_revision = 'd411ef171a52'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organizations', sa.Column('mailing_address', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organizations', 'mailing_address')
    # ### end Alembic commands ###
