"""added_cert_model

Revision ID: 96f5f0d0fe36
Revises: 4639870c527e
Create Date: 2024-02-01 10:48:17.480606

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '96f5f0d0fe36'
down_revision = '4639870c527e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('certs',
    sa.Column('date_added', sa.Date(), nullable=False),
    sa.Column('date_updated', sa.Date(), nullable=True),
    sa.Column('cert_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=True),
    sa.Column('type', sa.String(length=1), nullable=True),
    sa.Column('date_actual_resp', sa.Date(), nullable=True),
    sa.Column('org_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.org_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('cert_id'),
    sa.UniqueConstraint('uuid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('certs')
    # ### end Alembic commands ###
