"""added comment field to OrgAdmDocOrganization model

Revision ID: 9b21fc22c8d7
Revises: 2fa6a49e4b38
Create Date: 2022-12-07 17:40:59.008670

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '9b21fc22c8d7'
down_revision = '2fa6a49e4b38'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orgadmdocs_organizations', sa.Column('comment', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orgadmdocs_organizations', 'comment')
    # ### end Alembic commands ###
