"""file_extension added to support non-pdf files

Revision ID: cc72a6a0aec5
Revises: 2a1af46743ed
Create Date: 2023-02-07 14:58:06.956942

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'cc72a6a0aec5'
down_revision = '2a1af46743ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('methodical_docs', sa.Column('data_extension', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('methodical_docs', 'data_extension')
    # ### end Alembic commands ###
