"""added Contact

Revision ID: d411ef171a52
Revises: 3ff23da18617
Create Date: 2024-01-15 13:48:47.665558

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'd411ef171a52'
down_revision = '3ff23da18617'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contacts',
    sa.Column('date_added', sa.Date(), nullable=False),
    sa.Column('date_updated', sa.Date(), nullable=True),
    sa.Column('contact_id', sa.Integer(), nullable=False),
    sa.Column('fio', sa.String(length=254), nullable=True),
    sa.Column('dep', sa.String(length=254), nullable=True),
    sa.Column('pos', sa.String(length=254), nullable=True),
    sa.Column('mob_phone', sa.String(length=20), nullable=True),
    sa.Column('work_phone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=254), nullable=True),
    sa.Column('is_main', sa.Boolean(), nullable=True),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.org_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('contact_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('contacts')
    # ### end Alembic commands ###
