"""added name_for_letter column to MethodicalDoc

Revision ID: f4fc4c11eb45
Revises: 3b5fe85e2e25
Create Date: 2023-02-16 11:48:53.399310

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'f4fc4c11eb45'
down_revision = '3b5fe85e2e25'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('methodical_docs', sa.Column('name_for_letter', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('methodical_docs', 'name_for_letter')
    # ### end Alembic commands ###
