"""rofel

Revision ID: 130f740af069
Revises: 
Create Date: 2022-07-04 15:41:21.724503

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '130f740af069'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('industries',
    sa.Column('date_added', sa.Date(), nullable=False),
    sa.Column('date_updated', sa.Date(), nullable=True),
    sa.Column('industry_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('industry_id')
    )
    op.create_table('messages',
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('date_inbox_approved', sa.Date(), nullable=True),
    sa.Column('number_inbox_approved', sa.String(length=70), nullable=True),
    sa.Column('date_registered', sa.Date(), nullable=True),
    sa.Column('our_inbox_number', sa.String(length=70), nullable=True),
    sa.Column('date_approved', sa.Date(), nullable=True),
    sa.Column('our_outbox_number', sa.String(length=70), nullable=True),
    sa.Column('information', sa.Text(), nullable=False),
    sa.Column('datetime_created', sa.DateTime(), nullable=True),
    sa.Column('datetime_updated', sa.DateTime(), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['messages.message_id'], ),
    sa.PrimaryKeyConstraint('message_id')
    )
    op.create_table('methodical_docs',
    sa.Column('date_added', sa.Date(), nullable=False),
    sa.Column('date_updated', sa.Date(), nullable=True),
    sa.Column('method_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('date_approved', sa.Date(), nullable=True),
    sa.Column('props', sa.Text(), nullable=True),
    sa.Column('path_prefix', sa.Text(), nullable=False),
    sa.Column('is_conf', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('method_id')
    )
    op.create_table('okrugs',
    sa.Column('okrug_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('okrug_id')
    )
    op.create_table('orgadm_docs',
    sa.Column('date_added', sa.Date(), nullable=False),
    sa.Column('date_updated', sa.Date(), nullable=True),
    sa.Column('orgadm_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('name_prefix', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('orgadm_id')
    )
    op.create_table('methodicaldocs_messages',
    sa.Column('method_id', sa.Integer(), nullable=True),
    sa.Column('message_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['message_id'], ['messages.message_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['method_id'], ['methodical_docs.method_id'], ondelete='CASCADE')
    )
    op.create_table('regions',
    sa.Column('region_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=70), nullable=False),
    sa.Column('okrug_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['okrug_id'], ['okrugs.okrug_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('region_id')
    )
    op.create_table('addresses',
    sa.Column('index', sa.Integer(), nullable=False),
    sa.Column('area', sa.String(length=40), nullable=True),
    sa.Column('locality', sa.String(length=60), nullable=True),
    sa.Column('region_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['region_id'], ['regions.region_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('index')
    )
    op.create_index(op.f('ix_addresses_locality'), 'addresses', ['locality'], unique=False)
    op.create_table('organizations',
    sa.Column('date_added', sa.Date(), nullable=False),
    sa.Column('date_updated', sa.Date(), nullable=True),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('db_name', sa.Text(), nullable=False),
    sa.Column('full_name', sa.Text(), nullable=False),
    sa.Column('short_name', sa.Text(), nullable=True),
    sa.Column('inn', sa.BigInteger(), nullable=True),
    sa.Column('ogrn', sa.BigInteger(), nullable=True),
    sa.Column('factual_address', sa.Text(), nullable=True),
    sa.Column('boss_position', sa.String(length=200), nullable=True),
    sa.Column('boss_fio', sa.String(length=200), nullable=True),
    sa.Column('contacts', sa.Text(), nullable=True),
    sa.Column('date_agreement', sa.Date(), nullable=True),
    sa.Column('agreement_unit', sa.Text(), nullable=True),
    sa.Column('is_gov', sa.Boolean(), nullable=True),
    sa.Column('is_military', sa.Boolean(), nullable=True),
    sa.Column('is_ampel', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('uuid', sa.String(length=36), nullable=True),
    sa.Column('region_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['region_id'], ['regions.region_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('org_id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index(op.f('ix_organizations_date_agreement'), 'organizations', ['date_agreement'], unique=False)
    op.create_index(op.f('ix_organizations_db_name'), 'organizations', ['db_name'], unique=False)
    op.create_index(op.f('ix_organizations_inn'), 'organizations', ['inn'], unique=False)
    op.create_index(op.f('ix_organizations_ogrn'), 'organizations', ['ogrn'], unique=False)
    op.create_table('orgadmdocs_organizations',
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('orgadm_id', sa.Integer(), nullable=False),
    sa.Column('date_approved', sa.Date(), nullable=True),
    sa.Column('props', sa.Text(), nullable=True),
    sa.Column('our_inbox_number', sa.String(length=7), nullable=True),
    sa.Column('inventory_number', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.org_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['orgadm_id'], ['orgadm_docs.orgadm_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('org_id', 'orgadm_id')
    )
    op.create_table('organizations_messages',
    sa.Column('org_id', sa.Integer(), nullable=True),
    sa.Column('message_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['message_id'], ['messages.message_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.org_id'], ondelete='CASCADE')
    )
    op.create_table('resources',
    sa.Column('date_added', sa.Date(), nullable=False),
    sa.Column('date_updated', sa.Date(), nullable=True),
    sa.Column('resource_id', sa.Integer(), nullable=False),
    sa.Column('is_okii', sa.Boolean(), nullable=True),
    sa.Column('fstec_reg_number', sa.String(length=15), nullable=True),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('category', sa.SmallInteger(), nullable=True),
    sa.Column('date_added_to_fstec', sa.Date(), nullable=True),
    sa.Column('date_updated_to_fstec', sa.Date(), nullable=True),
    sa.Column('factual_addresses', sa.Text(), nullable=True),
    sa.Column('resp_worker', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('ip_pool', sa.Text(), nullable=True),
    sa.Column('dns_pool', sa.Text(), nullable=True),
    sa.Column('uuid', sa.String(length=36), nullable=True),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.org_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('resource_id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index(op.f('ix_resources_category'), 'resources', ['category'], unique=False)
    op.create_table('industries_resources',
    sa.Column('industry_id', sa.Integer(), nullable=True),
    sa.Column('resource_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['industry_id'], ['industries.industry_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resource_id'], ['resources.resource_id'], ondelete='CASCADE')
    )
    op.create_table('regions_resources',
    sa.Column('region_id', sa.Integer(), nullable=True),
    sa.Column('resource_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['region_id'], ['regions.region_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resource_id'], ['resources.resource_id'], ondelete='CASCADE')
    )
    op.create_table('responsibilities',
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('resource_id', sa.Integer(), nullable=False),
    sa.Column('date_start', sa.Date(), nullable=False),
    sa.Column('date_end', sa.Date(), nullable=False),
    sa.Column('props', sa.Text(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.org_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resource_id'], ['resources.resource_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('org_id', 'resource_id', 'date_end')
    )
    op.create_index(op.f('ix_responsibilities_date_end'), 'responsibilities', ['date_end'], unique=False)
    op.create_index(op.f('ix_responsibilities_date_start'), 'responsibilities', ['date_start'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_responsibilities_date_start'), table_name='responsibilities')
    op.drop_index(op.f('ix_responsibilities_date_end'), table_name='responsibilities')
    op.drop_table('responsibilities')
    op.drop_table('regions_resources')
    op.drop_table('industries_resources')
    op.drop_index(op.f('ix_resources_category'), table_name='resources')
    op.drop_table('resources')
    op.drop_table('organizations_messages')
    op.drop_table('orgadmdocs_organizations')
    op.drop_index(op.f('ix_organizations_ogrn'), table_name='organizations')
    op.drop_index(op.f('ix_organizations_inn'), table_name='organizations')
    op.drop_index(op.f('ix_organizations_db_name'), table_name='organizations')
    op.drop_index(op.f('ix_organizations_date_agreement'), table_name='organizations')
    op.drop_table('organizations')
    op.drop_index(op.f('ix_addresses_locality'), table_name='addresses')
    op.drop_table('addresses')
    op.drop_table('regions')
    op.drop_table('methodicaldocs_messages')
    op.drop_table('orgadm_docs')
    op.drop_table('okrugs')
    op.drop_table('methodical_docs')
    op.drop_table('messages')
    op.drop_table('industries')
    # ### end Alembic commands ###
