"""added large binary column to Methodical Doc

Revision ID: 19f8924404fa
Revises: 245123e0729e
Create Date: 2023-02-06 11:01:31.021565

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19f8924404fa'
down_revision = '245123e0729e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('methodical_docs', sa.Column('data', sa.LargeBinary(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('methodical_docs', 'data')
    # ### end Alembic commands ###
