"""added is_inbox to message

Revision ID: 3b5fe85e2e25
Revises: cc72a6a0aec5
Create Date: 2023-02-13 18:45:50.462443

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b5fe85e2e25'
down_revision = 'cc72a6a0aec5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('is_inbox', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'is_inbox')
    # ### end Alembic commands ###
